/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class AdditionalName implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String name1;
    private String name2;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(name1 != null) {
            nodeWriter.write(delimiters.escape(name1.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(name2 != null) {
            nodeWriter.write(delimiters.escape(name2.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getName1() {
        return name1;
    }

    public AdditionalName setName1(String name1) {
        this.name1 = name1;  return this;
    }

    public String getName2() {
        return name2;
    }

    public AdditionalName setName2(String name2) {
        this.name2 = name2;  return this;
    }
}