/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class AddressInformation implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String address1;
    private String address2;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(address1 != null) {
            nodeWriter.write(delimiters.escape(address1.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(address2 != null) {
            nodeWriter.write(delimiters.escape(address2.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getAddress1() {
        return address1;
    }

    public AddressInformation setAddress1(String address1) {
        this.address1 = address1;  return this;
    }

    public String getAddress2() {
        return address2;
    }

    public AddressInformation setAddress2(String address2) {
        this.address2 = address2;  return this;
    }
}