/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class AdministrativeCommunicationsContact implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String contactFunctionCode;
    private String name;
    private String communicationNumberQualifier;
    private String communicationNumber;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(contactFunctionCode != null) {
            nodeWriter.write(delimiters.escape(contactFunctionCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(name != null) {
            nodeWriter.write(delimiters.escape(name.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(communicationNumberQualifier != null) {
            nodeWriter.write(delimiters.escape(communicationNumberQualifier.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(communicationNumber != null) {
            nodeWriter.write(delimiters.escape(communicationNumber.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getContactFunctionCode() {
        return contactFunctionCode;
    }

    public AdministrativeCommunicationsContact setContactFunctionCode(String contactFunctionCode) {
        this.contactFunctionCode = contactFunctionCode;  return this;
    }

    public String getName() {
        return name;
    }

    public AdministrativeCommunicationsContact setName(String name) {
        this.name = name;  return this;
    }

    public String getCommunicationNumberQualifier() {
        return communicationNumberQualifier;
    }

    public AdministrativeCommunicationsContact setCommunicationNumberQualifier(String communicationNumberQualifier) {
        this.communicationNumberQualifier = communicationNumberQualifier;  return this;
    }

    public String getCommunicationNumber() {
        return communicationNumber;
    }

    public AdministrativeCommunicationsContact setCommunicationNumber(String communicationNumber) {
        this.communicationNumber = communicationNumber;  return this;
    }
}