/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Currency implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String entityIdentifierCode;
    private String currencyCode;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(entityIdentifierCode != null) {
            nodeWriter.write(delimiters.escape(entityIdentifierCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(currencyCode != null) {
            nodeWriter.write(delimiters.escape(currencyCode.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getEntityIdentifierCode() {
        return entityIdentifierCode;
    }

    public Currency setEntityIdentifierCode(String entityIdentifierCode) {
        this.entityIdentifierCode = entityIdentifierCode;  return this;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public Currency setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;  return this;
    }
}