/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class GeographicLocation implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String cityName;
    private String stateCode;
    private String postalCode;
    private String countryCode;
    private String locationQualifier;
    private String locationIdentifier;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(cityName != null) {
            nodeWriter.write(delimiters.escape(cityName.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(stateCode != null) {
            nodeWriter.write(delimiters.escape(stateCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(postalCode != null) {
            nodeWriter.write(delimiters.escape(postalCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(countryCode != null) {
            nodeWriter.write(delimiters.escape(countryCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(locationQualifier != null) {
            nodeWriter.write(delimiters.escape(locationQualifier.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(locationIdentifier != null) {
            nodeWriter.write(delimiters.escape(locationIdentifier.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getCityName() {
        return cityName;
    }

    public GeographicLocation setCityName(String cityName) {
        this.cityName = cityName;  return this;
    }

    public String getStateCode() {
        return stateCode;
    }

    public GeographicLocation setStateCode(String stateCode) {
        this.stateCode = stateCode;  return this;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public GeographicLocation setPostalCode(String postalCode) {
        this.postalCode = postalCode;  return this;
    }

    public String getCountryCode() {
        return countryCode;
    }

    public GeographicLocation setCountryCode(String countryCode) {
        this.countryCode = countryCode;  return this;
    }

    public String getLocationQualifier() {
        return locationQualifier;
    }

    public GeographicLocation setLocationQualifier(String locationQualifier) {
        this.locationQualifier = locationQualifier;  return this;
    }

    public String getLocationIdentifier() {
        return locationIdentifier;
    }

    public GeographicLocation setLocationIdentifier(String locationIdentifier) {
        this.locationIdentifier = locationIdentifier;  return this;
    }
}