/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Name implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String organizationType;
    private String name;
    private String idCodeQualifier;
    private String idCode;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(organizationType != null) {
            nodeWriter.write(delimiters.escape(organizationType.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(name != null) {
            nodeWriter.write(delimiters.escape(name.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(idCodeQualifier != null) {
            nodeWriter.write(delimiters.escape(idCodeQualifier.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(idCode != null) {
            nodeWriter.write(delimiters.escape(idCode.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getOrganizationType() {
        return organizationType;
    }

    public Name setOrganizationType(String organizationType) {
        this.organizationType = organizationType;  return this;
    }

    public String getName() {
        return name;
    }

    public Name setName(String name) {
        this.name = name;  return this;
    }

    public String getIdCodeQualifier() {
        return idCodeQualifier;
    }

    public Name setIdCodeQualifier(String idCodeQualifier) {
        this.idCodeQualifier = idCodeQualifier;  return this;
    }

    public String getIdCode() {
        return idCode;
    }

    public Name setIdCode(String idCode) {
        this.idCode = idCode;  return this;
    }
}