/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Note implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String noteReferenceCode;
    private String description;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(noteReferenceCode != null) {
            nodeWriter.write(delimiters.escape(noteReferenceCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(description != null) {
            nodeWriter.write(delimiters.escape(description.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getNoteReferenceCode() {
        return noteReferenceCode;
    }

    public Note setNoteReferenceCode(String noteReferenceCode) {
        this.noteReferenceCode = noteReferenceCode;  return this;
    }

    public String getDescription() {
        return description;
    }

    public Note setDescription(String description) {
        this.description = description;  return this;
    }
}