/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class ReferenceNumber implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String referenceNumberQualifier;
    private String referenceNumber;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(referenceNumberQualifier != null) {
            nodeWriter.write(delimiters.escape(referenceNumberQualifier.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(referenceNumber != null) {
            nodeWriter.write(delimiters.escape(referenceNumber.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getReferenceNumberQualifier() {
        return referenceNumberQualifier;
    }

    public ReferenceNumber setReferenceNumberQualifier(String referenceNumberQualifier) {
        this.referenceNumberQualifier = referenceNumberQualifier;  return this;
    }

    public String getReferenceNumber() {
        return referenceNumber;
    }

    public ReferenceNumber setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;  return this;
    }
}