/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.math.BigDecimal;    
import org.milyn.javabean.decoders.BigDecimalDecoder;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SpacInformation implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String allowanceChargeIndicator;
    private String spacCode;
    private BigDecimal amount;
    private BigDecimalDecoder amountEncoder;
    private String methodHandlingCode;

    public SpacInformation() {
        
        amountEncoder = new BigDecimalDecoder();
    }

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(allowanceChargeIndicator != null) {
            nodeWriter.write(delimiters.escape(allowanceChargeIndicator.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(spacCode != null) {
            nodeWriter.write(delimiters.escape(spacCode.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(amount != null) {
            nodeWriter.write(delimiters.escape(amountEncoder.encode(amount)));
        }
        nodeWriter.write(delimiters.getField());
        if(methodHandlingCode != null) {
            nodeWriter.write(delimiters.escape(methodHandlingCode.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getAllowanceChargeIndicator() {
        return allowanceChargeIndicator;
    }

    public SpacInformation setAllowanceChargeIndicator(String allowanceChargeIndicator) {
        this.allowanceChargeIndicator = allowanceChargeIndicator;  return this;
    }

    public String getSpacCode() {
        return spacCode;
    }

    public SpacInformation setSpacCode(String spacCode) {
        this.spacCode = spacCode;  return this;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public SpacInformation setAmount(BigDecimal amount) {
        this.amount = amount;  return this;
    }

    public String getMethodHandlingCode() {
        return methodHandlingCode;
    }

    public SpacInformation setMethodHandlingCode(String methodHandlingCode) {
        this.methodHandlingCode = methodHandlingCode;  return this;
    }
}