/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package com.acme.order.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.math.BigInteger;    
import org.milyn.javabean.decoders.BigIntegerDecoder;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class TransactionSetTrailer implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private BigInteger segmentsInTransaction;
    private BigIntegerDecoder segmentsInTransactionEncoder;
    private String transactionSetControl;

    public TransactionSetTrailer() {
        
        segmentsInTransactionEncoder = new BigIntegerDecoder();
    }

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(segmentsInTransaction != null) {
            nodeWriter.write(delimiters.escape(segmentsInTransactionEncoder.encode(segmentsInTransaction)));
        }
        nodeWriter.write(delimiters.getField());
        if(transactionSetControl != null) {
            nodeWriter.write(delimiters.escape(transactionSetControl.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public BigInteger getSegmentsInTransaction() {
        return segmentsInTransaction;
    }

    public TransactionSetTrailer setSegmentsInTransaction(BigInteger segmentsInTransaction) {
        this.segmentsInTransaction = segmentsInTransaction;  return this;
    }

    public String getTransactionSetControl() {
        return transactionSetControl;
    }

    public TransactionSetTrailer setTransactionSetControl(String transactionSetControl) {
        this.transactionSetControl = transactionSetControl;  return this;
    }
}